// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectTag is the predicate function for projecttag builders.
type ProjectTag func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserTechnology is the predicate function for usertechnology builders.
type UserTechnology func(*sql.Selector)
